---
# Homepage configuration
# See https://fontawesome.com/icons for icons options
# Optional: Use external configuration file.
# Using this will ignore remaining config in this file
# externalConfig: https://example.com/server-luci/config.yaml

title: "Home"
subtitle: "Chandler's Dashboard"
# logo: false
icon: "fas fa-home" # Optional icon

header: true # Set to false to hide the header
footer: false

columns: "auto" # "auto" or number (must be a factor of 12: 1, 2, 3, 4, 6, 12)
connectivityCheck: false # whether you want to display a message when the apps are not accessible anymore (VPN disconnected for example)

# Here is the exaustive list of customization parameters
# However all value are optional and will fallback to default if not set.
# if you want to change only some of the colors, feel free to remove all unused key.
colors:
  light:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#ffffff"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link-hover: "#363636"
  dark:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link-hover: "#ffdd57"

# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
links: []
# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).

services:
  - name: "Work"
    icon: "fas fa-building"
    items:
      - name: "GitHub"
        logo: "https://camo.githubusercontent.com/b079fe922f00c4b86f1b724fbc2e8141c468794ce8adbc9b7456e5e1ad09c622/68747470733a2f2f6564656e742e6769746875622e696f2f537570657254696e7949636f6e732f696d616765732f7376672f6769746875622e737667"
        tag: "work"
        url: "https://github.com/"

      - name: "Pillar GitHub"
        logo: "assets/tools/pillar.png"
        subtitle: ""
        tag: "work"
        url: "https://github.com/pillargg"

      - name: "Pillar Vercel"
        logo: "assets/tools/vercel.png"
        url: "https://vercel.com/pillargg"
        tag: "work"

      - name: "AWS Dashboard"
        logo: "https://camo.githubusercontent.com/7c3bb60d7d467ae8a60ebc9b6ff8a78cf7f45b18d16570fc7b8533d9c513acca/68747470733a2f2f6564656e742e6769746875622e696f2f537570657254696e7949636f6e732f696d616765732f7376672f616d617a6f6e2e737667"
        url: "https://console.aws.amazon.com/"
        tag: "work"

      - name: "Linode Dashboard"
        logo: "assets/tools/linode.png"
        url: "https://cloud.linode.com"
        tag: "work"

      - name: "My Vercel"
        logo: "assets/tools/vercel.png"
        url: "https://vercel.com/chand1012"
        tag: "work"

      - name: "Hubspot Dashboard"
        logo: "assets/tools/hubspot.png"
        url: "https://app.hubspot.com"
        tag: "work"

      - name: "Oracle Cloud"
        logo: "assets/tools/oracle.png"
        url: "https://cloud.oracle.com"
        tag: "work"

  - name: "Frequent Links"
    icon: "far fa-clock"
    items:
      - name: "YouTube"
        tag: "frequent"
        logo: "https://camo.githubusercontent.com/d54e97f5edde790381f7e62b217410df33e066a0dc8f692f2fc6b25fc1768b0c/68747470733a2f2f6564656e742e6769746875622e696f2f537570657254696e7949636f6e732f696d616765732f7376672f796f75747562652e737667"
        subtitle: ""
        url: "https://youtube.com/"

      - name: "Reddit"
        tag: "frequent"
        logo: "https://camo.githubusercontent.com/521640dc2dba501cde1805c0a42cecf5ccf7fc1378f542fe9fda756fb36add25/68747470733a2f2f6564656e742e6769746875622e696f2f537570657254696e7949636f6e732f696d616765732f7376672f7265646469742e737667"
        url: "https://reddit.com/"

      - name: "Twitch"
        logo: "https://camo.githubusercontent.com/c5942c39052ad962364ea8286a6991f7a9b036bf1d96d20db346d9dfd844dfa4/68747470733a2f2f6564656e742e6769746875622e696f2f537570657254696e7949636f6e732f696d616765732f7376672f7477697463682e737667"
        subtitle: ""
        tag: "frequent"
        url: "https://twitch.tv/"

      - name: "Gfycat"
        logo: "assets/tools/gfycat.png"
        tag: "frequent"
        url: "https://gfycat.com/"

      - name: "Gmail"
        logo: "https://camo.githubusercontent.com/4a3dd8d10a27c272fd04b2ce8ed1a130606f95ea6a76b5e19ce8b642faa18c27/68747470733a2f2f6564656e742e6769746875622e696f2f537570657254696e7949636f6e732f696d616765732f7376672f676d61696c2e737667"
        subtitle: ""
        tag: "frequent"
        url: "https://mail.google.com/"

      - name: "Personal Outlook"
        logo: "https://camo.githubusercontent.com/0f3aa1f457bb92fbd2411761262ce1fb0f766ed74a4f4289bfc4a0b6024335d6/68747470733a2f2f6564656e742e6769746875622e696f2f537570657254696e7949636f6e732f696d616765732f7376672f656d61696c2e737667"
        subtitle: ""
        tag: "frequent"
        url: "https://outlook.live.com/"

      - name: "My Blog"
        logo: "https://www.chand1012.dev/static/f866fe45236598e4c94f1cface3f9fee/3faea/profile-pic.webp"
        tag: "frequent"
        url: "https://www.chand1012.dev/"

      - name: "Dev.to"
        logo: "https://camo.githubusercontent.com/6cc90061976bcd4d1a61a6c76b818538b5a65754f7b7b8068fe0fa49a09def8f/68747470733a2f2f6564656e742e6769746875622e696f2f537570657254696e7949636f6e732f696d616765732f7376672f6465765f746f2e737667"
        tag: "frequent"
        url: "https://dev.to"

  - name: "School"
    icon: "fas fa-school"
    items:
      - name: "My UAkron"
        logo: "assets/tools/uakron.png"
        tag: "school"
        url: "https://my.uakron.edu/"

      - name: "School Outlook"
        logo: "https://camo.githubusercontent.com/21863a9a063d33b20608be917f5601f309abec90ae5cf5dedea38bb6b55d11ab/68747470733a2f2f6564656e742e6769746875622e696f2f537570657254696e7949636f6e732f696d616765732f7376672f6d61696c2e737667"
        tag: "school"
        url: "https://outlook.office.com/"

      - name: "Spanish VHL"
        logo: "assets/tools/spain.png"
        tag: "school"
        url: "https://www.vhlcentral.com/"

      - name: "Dr. Xiao's ISP Class"
        logo: "https://camo.githubusercontent.com/0d33c2c2ed78a0b87f51f91c5c3d9ff012d3b2d4e733b7133b82196b7310e1e3/68747470733a2f2f6564656e742e6769746875622e696f2f537570657254696e7949636f6e732f696d616765732f7376672f776966692e737667"
        tag: "school"
        url: "http://www.cs.uakron.edu/%7Exiao/isp/index.html"

  - name: "Local Services"
    icon: "fas fa-home"
    items:
      - name: "UnRAID"
        logo: "assets/tools/unraid.png"
        subtitle: "My NAS"
        tag: "local"
        url: "http://192.168.1.22"

      - name: "Octoprint"
        logo: "https://octoprint.org/assets/img/logo.png"
        subtitle: "3D Print Server"
        url: "http://192.168.1.17"
        tag: "local"
# Template:
#  - name: ""
#    icon: "fab fa-code-fork"
#    items:
#      - name: ""
#        icon: ""
#        tag: "service"
#        url: "https://"

